package com.wanderwildwood.zatsuno.knots

import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import com.wanderwildwood.zatsuno.R

/** One knot: its name, what it is for in a line, and its steps, each a drawing and a sentence. */
data class Knot(
    val id: String,
    @StringRes val name: Int,
    @StringRes val use: Int,
    val steps: List<Step>,
)

data class Step(@DrawableRes val drawing: Int, @StringRes val caption: Int)

/**
 * The knots, simplest first. The drawings are generated by tools/make-knots.py; each step is
 * the same rope as the one after it, cut short, with an open arrow on the end showing where
 * it goes next.
 */
object Knots {
    val all: List<Knot> = listOf(
        Knot("overhand", R.string.knot_overhand, R.string.knot_overhand_use, listOf(
            Step(R.drawable.knot_overhand_1, R.string.knot_overhand_1),
            Step(R.drawable.knot_overhand_2, R.string.knot_overhand_2),
        )),
        Knot("figure_eight", R.string.knot_figure_eight, R.string.knot_figure_eight_use, listOf(
            Step(R.drawable.knot_figure_eight_1, R.string.knot_figure_eight_1),
            Step(R.drawable.knot_figure_eight_2, R.string.knot_figure_eight_2),
            Step(R.drawable.knot_figure_eight_3, R.string.knot_figure_eight_3),
        )),
        Knot("figure_eight_loop", R.string.knot_figure_eight_loop, R.string.knot_figure_eight_loop_use, listOf(
            Step(R.drawable.knot_figure_eight_loop_1, R.string.knot_figure_eight_loop_1),
            Step(R.drawable.knot_figure_eight_loop_2, R.string.knot_figure_eight_loop_2),
        )),
        Knot("bowline", R.string.knot_bowline, R.string.knot_bowline_use, listOf(
            Step(R.drawable.knot_bowline_1, R.string.knot_bowline_1),
            Step(R.drawable.knot_bowline_2, R.string.knot_bowline_2),
            Step(R.drawable.knot_bowline_3, R.string.knot_bowline_3),
        )),
        Knot("clove_hitch", R.string.knot_clove_hitch, R.string.knot_clove_hitch_use, listOf(
            Step(R.drawable.knot_clove_hitch_1, R.string.knot_clove_hitch_1),
            Step(R.drawable.knot_clove_hitch_2, R.string.knot_clove_hitch_2),
            Step(R.drawable.knot_clove_hitch_3, R.string.knot_clove_hitch_3),
        )),
        Knot("two_half_hitches", R.string.knot_two_half_hitches, R.string.knot_two_half_hitches_use, listOf(
            Step(R.drawable.knot_two_half_hitches_1, R.string.knot_two_half_hitches_1),
            Step(R.drawable.knot_two_half_hitches_2, R.string.knot_two_half_hitches_2),
            Step(R.drawable.knot_two_half_hitches_3, R.string.knot_two_half_hitches_3),
        )),
        Knot("taut_line", R.string.knot_taut_line, R.string.knot_taut_line_use, listOf(
            Step(R.drawable.knot_taut_line_1, R.string.knot_taut_line_1),
            Step(R.drawable.knot_taut_line_2, R.string.knot_taut_line_2),
            Step(R.drawable.knot_taut_line_3, R.string.knot_taut_line_3),
        )),
        Knot("sheet_bend", R.string.knot_sheet_bend, R.string.knot_sheet_bend_use, listOf(
            Step(R.drawable.knot_sheet_bend_1, R.string.knot_sheet_bend_1),
            Step(R.drawable.knot_sheet_bend_2, R.string.knot_sheet_bend_2),
            Step(R.drawable.knot_sheet_bend_3, R.string.knot_sheet_bend_3),
        )),
        Knot("square_knot", R.string.knot_square_knot, R.string.knot_square_knot_use, listOf(
            Step(R.drawable.knot_square_knot_1, R.string.knot_square_knot_1),
            Step(R.drawable.knot_square_knot_2, R.string.knot_square_knot_2),
            Step(R.drawable.knot_square_knot_3, R.string.knot_square_knot_3),
        )),
        Knot("prusik", R.string.knot_prusik, R.string.knot_prusik_use, listOf(
            Step(R.drawable.knot_prusik_1, R.string.knot_prusik_1),
            Step(R.drawable.knot_prusik_2, R.string.knot_prusik_2),
        )),
        Knot("double_fishermans", R.string.knot_double_fishermans, R.string.knot_double_fishermans_use, listOf(
            Step(R.drawable.knot_double_fishermans_1, R.string.knot_double_fishermans_1),
            Step(R.drawable.knot_double_fishermans_2, R.string.knot_double_fishermans_2),
            Step(R.drawable.knot_double_fishermans_3, R.string.knot_double_fishermans_3),
        )),
        Knot("timber_hitch", R.string.knot_timber_hitch, R.string.knot_timber_hitch_use, listOf(
            Step(R.drawable.knot_timber_hitch_1, R.string.knot_timber_hitch_1),
            Step(R.drawable.knot_timber_hitch_2, R.string.knot_timber_hitch_2),
            Step(R.drawable.knot_timber_hitch_3, R.string.knot_timber_hitch_3),
        )),
    )

    fun find(id: String): Knot? = all.firstOrNull { it.id == id }
}
